#!/usr/bin/perl -w

use Linux::LVM;

Linux::LVM->units(B);

if (@ARGV < 2){
    usage();
    exit(1);
}

my $vol = $ARGV[0];
my $what = $ARGV[1];

sub usage {
    print<<"EOF";

Usage: $0 <logical volume> [size|allocation|status]

EOF
}

my %info = get_lv_info($vol);

if ($what eq 'size'){
    print $info{size};
}
elsif ($what eq 'allocation'){
    my $ret = (defined $info{allocated_to_snapshot}) ? $info{allocated_to_snapshot} : "ZBX_NOTSUPPORTED";
    $ret =~ s/,/\./;
    print $ret;
}
elsif ($what eq 'status'){
    print $info{status};
}
else{
    usage();
}
exit(0);
