#!/usr/bin/perl -w

use warnings;
use strict;
use Zabbix::Agent::Addons::Disks;
use JSON;

my $json;
@{$json->{data}} = ();

foreach my $block (Zabbix::Agent::Addons::Disks::list_smart_hdd({ skip_remouvable => 1 })){
  push @{$json->{data}}, { "{#SMARTDRIVE}" => "/dev/$block" };
}
print to_json($json);
exit(0);
