#!/usr/bin/perl -w

use JSON;
use Zabbix::Agent::Addons::UPS;

my $json;
@{$json->{data}} = ();

foreach my $ups (Zabbix::Agent::Addons::UPS::list_ups()){
  push @{$json->{data}}, {"{#UPSNAME}" => $ups};
}
print to_json($json);
exit(0);
