#!/usr/bin/perl -w

use strict;
use JSON;

my $json;
@{$json->{data}} = ();

if (!-x '/usr/bin/systemd-detect-virt' || system('/usr/bin/systemd-detect-virt', '-qc') != 0){
  open FILE, "< /proc/mdstat" or die "Can't open /proc/mdadm : $!";
  foreach my $line (<FILE>) {
    next unless ($line =~ m/^(md\d+)+\s*:/);
    my ($md,undef,$status,$level) = split(/\ /, $line);
    push @{$json->{data}}, {"{#DEVICE}" => $md, "{#STATUS}" => $status, "{#LEVEL}" => $level};
  }
}
print to_json($json);
exit(0);
